### ISSUE TITLE
Not working in Windows

### ISSUE THREAD

**Issue by levys86** [hdima/erlport#19]
Using Windows XP and Windows 7, Erlport can't find the python interpreter.
It works without a hitch in Debian.

I've tried various combinations of environment variables and python:start() options.
python:start([{python, "C:\Python27"}]). and all combinations of that directory.
error: invalid_option, {python, "c:\\Python27"}, not_found}}
If I add a \ to the end of that path, it just sits there doing nothing forever until I kill the process.

It looks like ERLPORT_PYTHON is the correct env var to set the interpreter path,
{error,{invalid_env_var,{"ERLPORT_PYTHON","c:\\python27"), not_found}}

After messing around with it for a while, I found the root cause is a missing python entry in the PATH env var. after adding the python folder to PATH, I was able to run erlport without setting any options.

Just posting this info for other people who may have this problem.

**Comment by filmor** [comment]
Would you mind closing this? Erlport is working fine on Windows, this is a simple user error ...
