### ISSUE TITLE
Insensible Python3 Type Mapping 

### ISSUE THREAD

**Issue by heri16** [hdima/erlport#23]
While trying to call boto.s3.connection S3Connection.get_bucket method in Python3, realised that there is no way to pass in a str() in Python3.

Erlang Char lists (string) become lists in Python 3. Erlang binary becomes bytes in Python3. But using bytes.decode in python3 results in a char list being returned back to the Erlang VM, instead of an opaque object that represents a python3 str(). Thus there is no way to pass in a str object to a method call.

**Comment by hdima** [comment]
Unfortunately there's no reliable way to distinguish a list from a "string" in Erlang. So Erlang lists mapped to [List](https://github.com/hdima/erlport/blob/master/priv/python3/erlport/erlterms.py#L78) class in ErlPort which is a subclass of `list` but also can be converted to Unicode string with [to_string()](https://github.com/hdima/erlport/blob/master/priv/python3/erlport/erlterms.py#L83) method.

I think there are at least two ways to pass `str` to Python 3 (both of them require some Python code unfortunately):

- A wrapper for a function can be created in Python which always convert string arguments to `str`. Something like the following code (*not tested*):
   
     ```python
    def get_bucket(connection, bucket_name):
        return connection.get_bucket(bucket_name.to_string())
    ```
- [Custom data type](http://erlport.org/docs/python.html#custom-data-types) decoder can be used to for example convert `{string, String}` Erlang tuple to `str` in Python. The code can look like this (*not tested*):

    ```python
    def str_decoder(value):
        if isinstance(value, tuple) and len(value) == 2 and value[0] == "string":
            value = value[1].to_string()
        return value
    ```

**Comment by jdoig** [comment]
I've managed to fix this for my uses (that is fire and forget calls from Elixir to Python) with the following:
in: `decode`
```Elixir
    elif tag == 109:
        # BINARY_EXT ... In Elixir this is a BitString
        ln = len(string)
        if ln < 5:
            raise IncompleteData(string)
        length = int4_unpack(string[1:5])[0] + 5
        if ln < length:
            raise IncompleteData(string)
        stringy = string[5:length]
        return stringy.decode(), string[length:]
```
and in `OpaqueObject`:
```Elixir
    @classmethod
    def decode(cls, data, language):
        if isinstance(data, str):
            data = data.encode()
        if language == b"python":
            return loads(data)
        return cls(data, language)
```
here: https://github.com/jdoig/erlport

My requirements are very simple so I've no idea the overall impact of doing this or how this would work with erlang. Just leaving this here in case any one arrives via a search.
