### ISSUE TITLE
Cannot Pickle built-in Python objects

### ISSUE THREAD

**Issue by heri16** [hdima/erlport#24]
Since erlport cannot do variable assignments without pickling to erlang, I had met with the following problem:
http://stackoverflow.com/questions/7107409/why-does-pickle-protocol-2-let-me-serialise-an-open-file-object

```elixir
iex(33)> fp = :python.call(pid, :'__builtin__', :'open', ["test.log", "r+"])
iex(34)> :python.call(pid, :'__builtin__', :'repr', [fp])
"<closed file '<uninitialized file>', mode '<uninitialized file>' at 0x106003ae0>"
```

It is suggested to switch from pickle to dill (https://github.com/uqfoundation/dill).
Dill can pickle the following standard types::

none, type, bool, int, long, float, complex, str, unicode,
tuple, list, dict, file, buffer, builtin,
both old and new style classes,
instances of old and new style classes,
set, frozenset, array, functions, exceptions
Dill can also pickle more 'exotic' standard types::

functions with yields, nested functions, lambdas
cell, method, unboundmethod, module, code, methodwrapper,
dictproxy, methoddescriptor, getsetdescriptor, memberdescriptor,
wrapperdescriptor, xrange, slice,
notimplemented, ellipsis, quit

**Comment by hdima** [comment]
Open file objects can't be pickled for a reason. They connected to file descriptors which belongs to the process. So you can't for example transfer them to another process and get the same result.

In `dill` they try to fix it in some hackish way by for example reopening the file. So if you want to use `dill` you really need to know what you're doing. And it's not suitable for generic case for sure.

If you want to use `dill` in your project you can add a [custom data type](http://erlport.org/docs/python.html#custom-data-types) for file objects. But I think the better way is to store files (or higher level objects which own the files) in a `dict` on Python side and return only a key to Erlang.
