### ISSUE TITLE
Cast/Call from Python to erlang?

### ISSUE THREAD

**Issue by vans163** [hdima/erlport#30]
Looking at docs it shows to use:

from erlport.erlang import call

but in the erlport/erlang.py call is not even exposed its inside def MessageHandler(object):

Maybe I am doing something wrong or the documentation is outdated?

EDIT:  I kind of hacked together a cast which is really not a cast but a send using:
```
from erlport.erlterms import Atom
from erlport.erlproto import Port

port = Port()
port.write((Atom('M'), fromerlang_pid, "hi"))
```

**Comment by hdima** [comment]
Python processes must be bootstrapped from Erlang first for ErlPort to work. Internally ErlPort uses [open_port/2](http://erlang.org/doc/man/erlang.html#open_port-2) on Erlang side and on Python side all the functions in `erlport.erlang` module will be available after [erlang.setup(port)](https://github.com/hdima/erlport/blob/master/priv/python2/erlport/erlang.py#L274) call.

Please also see [How ErlPort works](http://erlport.org/docs/#how-erlport-works) and [Python instances](http://erlport.org/docs/python.html#python-instances) for more details.

**Comment by vans163** [comment]
Really? I read [Python instances](http://erlport.org/docs/python.html#python-instances) multiple times trying to see if I missed anything. 

I cannot find anything that said you need to call erlang.setup(port) or even how to do it. Even if you did it, you still cannot do cast(...) like how the documentation says.

**Comment by hdima** [comment]
You should *not* call `erlang.setup(port)` yourself. It's just internal implementation details which I though maybe interesting.

The simplest example of using `erlang.cast()` can be found in documentation - [Send messages from Python to Erlang](http://erlport.org/docs/python.html#send-messages-from-python-to-erlang). It's basically a fancy way to send `test_message` message to itself with `erlport.erlang.cast(self(), test_message)` call on Python side:

```erlang
1> {ok, P} = python:start().
{ok,<0.34.0>}
2> python:call(P, 'erlport.erlang', cast, [self(), test_message]).
undefined
3> flush().
Shell got test_message
ok
```

You can also put basically the same code in a Python module. For example you can create the following file with `test_cast.py` name:

```python
from erlport import erlang, Atom

def send_test_message(receiver):
    erlang.cast(receiver, Atom("test"))
```

And then call it from Erlang to send `test` message to itself:

```erlang
1> {ok, P} = python:start().
{ok,<0.35.0>}
2> python:call(P, test_cast, send_test_message, [self()]).
undefined
3> flush().
Shell got test
ok
```

**Comment by vans163** [comment]
I am amazed, as to how and why that works haha. Must be the way python works that I don't understand. cast is not even exposed inside erlang.py file, its in a class.  How can erlang.cast(..) call work?

Thank you for taking the time.

**Comment by hdima** [comment]
Well, as I said in the first comment it's bootstrapped by [erlang.setup(port)](https://github.com/hdima/erlport/blob/master/priv/python2/erlport/erlang.py#L263) or more precise by [erlang.setup_api_functions(handler)](https://github.com/hdima/erlport/blob/master/priv/python2/erlport/erlang.py#L247).
