### ISSUE TITLE
Port closed on erlport.cli, again

### ISSUE THREAD

**Issue by Mazyod** [hdima/erlport#32]
Running Erlport through Elixir, I was getting this error, and it was driving me nuts:

```
/usr/bin/python: No module named erlport.cli

** (ErlangError) erlang error: {:port_closed, {:code, 1}}

17:46:26.849 [error] GenServer #PID<0.128.0> terminating
** (stop) {:port_closed, {:code, 1}}
Last message: {#Port<0.5453>, {:exit_status, 1}}
State: {:state, :infinity, 0, #Port<0.5453>, [{1, {{#PID<0.126.0>, #Reference<0.0.5.24>}, :undefined}}], []}
    src/erlport.erl:234: :erlport.call/3
```

The way I resolved the issue was through:

```
pip uninstall erlport
```

Indeed, it seems that the erlport python module used internally is called "erlport", and so is the module used by external scripts, which caused this issue.

Perhaps consider renaming the internal python module?

**NOTE:** an issue about this seems to have been raised before here #6

**Comment by Mazyod** [comment]
nvm, just remove erlport from pip, and rely on erlport loading the python module at runtime works fine.

**Comment by ghost** [comment]
Getting this error too, apparently `cli.py` has been removed from the python3 module: https://github.com/hdima/erlport/tree/master/priv/python3/erlport
