### ISSUE TITLE
Could not compile erlport

### ISSUE THREAD

**Issue by mladenp** [hdima/erlport#48]
I am getting this error compiling erlport:

`** (Mix) Could not compile dependency :erlport, "/Users/mladen/.mix/rebar3 bare compile --paths "/Users/mladen/work/inSITE_Search/_build/dev/lib/*/ebin"" command failed.`

I am getting this on a freshly installed macOS high sierra, while i never got this error on other Macs i tried.
I only found one user with similar error but without much luck fixing it: 
https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=sr&ie=UTF-8&u=https%3A%2F%2Fteratail.com%2Fquestions%2F114967&edit-text=&act=url

I am using default python that comes with mac (2.7) and i don't have erlport installed via pip.
I also don't get any error besides "could not compile" or i don't know here to look for error logs.

**Comment by jeffutter** [comment]
Are you using OTP 21? there is a depreciation warning with OTP 21. The rebar config for erlport converts warnings to errors so it doesn't build anymore. I think PR #47 will fix this.

**Comment by mladenp** [comment]
Hey thanks jeff, it actually works when i downgraded erlang to 20 and added it to path like so:
`/usr/local/opt/erlang@20/bin`
#47 PR doesn't seems to be working.
Thank you

**Comment by ilovemysillybanana** [comment]
did this ever get fixed? I require Erlang 21+ and am using this however I do not know how to build it myself and thanks to proxies am now having to do so but it keeps complaining.

**Comment by jeffutter** [comment]
@ilovemysillybanana in this repo, no, but it has been fixed over here: https://github.com/erlport/erlport which is also the repo that the `hex` package it being built from, if you use `hex`

**Comment by ilovemysillybanana** [comment]
@jeffutter Thank you, I'll reach out on that repo's issues.

**Comment by ilovemysillybanana** [comment]
@jeffutter Just wanting to clarify somethings.

You said the other repo you linked is the one used in the hex package, but which repo was used to create the binary packages on the website because they link to to this repo. And I am now wanting to try that out. 

Source:

http://erlport.org/downloads/

Says `git clone https://github.com/hdima/erlport.git`

**Comment by filmor** [comment]
hdima (the original author and owner of erlport.org) seems to have abandoned this project (no contact in ~4 years), so we made a new repository with all of the crucial PRs merged. There is no active development going on there either, but if you have a patch, you'll have a realistic chance of it getting merged there, version bumped and a hex package uploaded with it.
